# Generated by Django 4.2.5 on 2023-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('image', models.ImageField(upload_to='prof_pic/')),
                ('phone', models.TextField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('othes', 'others')], max_length=8)),
                ('deate_of_birth', models.DateTimeField()),
            ],
        ),
    ]
