# Generated by Django 4.2.5 on 2023-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deate_of_birth',
            field=models.DateField(),
        ),
    ]
